'use client';

import Link from "next/link";
import { useEffect, useState } from "react";

const report = {
  words: "Vi bruger for meget tid på manuelle mails, Excel-ark og opfølgninger. Jeg tror processen kan automatiseres, men jeg ved ikke hvad vi skal bygge, hvor vi skal starte, eller hvilken type specialist vi skal bruge.",
  title: "Eksempel: Analyse af behov for automatisering",
  understood: "Naetwork forstår behovet som en opgave, hvor en manuel og tidskrævende arbejdsproces skal gøres tydelig, før der vælges løsning eller specialist. Det centrale er først at forstå hvor friktionen opstår, hvilke trin der gentages, og hvad en brugbar første version bør indeholde.",
  need: "Behovet er at reducere manuel koordinering og skabe bedre overblik, så teamet bruger mindre tid på gentagne beskeder, Excel-ark og opfølgninger.",
  task: "Første opgave bør være at kortlægge workflowet, identificere de gentagne trin, definere en enkel første version og vurdere hvilke systemer eller værktøjer der skal indgå.",
  specialist: "Automationsspecialist med erfaring i interne workflows, simple integrationer og praktiske første versioner."
};

const scope = ["Kortlægge nuværende workflow", "Identificere gentagne mails og opfølgninger", "Definere første brugbare løsning", "Vurdere data, systemer og ansvar", "Anbefale specialistretning"];
const notNow = ["Bygge en stor platform fra dag ét", "Automatisere alt uden prioritering", "Vælge leverandør før opgaven er forstået"];
const questions = ["Hvem bruger processen i dag?", "Hvor ligger data?", "Hvilke trin gentages mest?", "Hvad er en god første version?"];

function Shell({ children }: { children: React.ReactNode }) {
  return <main className="min-h-screen bg-[#f7f8fb] px-4 py-6 text-slate-950 sm:px-5"><header className="mx-auto flex max-w-6xl items-center justify-between py-3"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#071527] text-sm font-black text-white">N</span><span className="text-lg font-black tracking-tight text-[#071527]">Naetwork</span></Link><Link href="/min-side" className="rounded-full bg-[#071527] px-4 py-2 text-sm font-black text-white shadow-sm">Min profil</Link></header>{children}</main>;
}

function StaticReport() {
  return <article className="mx-auto w-full max-w-[780px] rounded-[20px] border border-slate-200 bg-white p-7 shadow-sm sm:p-9"><div className="border-b border-slate-200 pb-6"><p className="text-xs font-black uppercase tracking-[.22em] text-[#3f8f83]">Statisk eksempel</p><h2 className="mt-3 text-3xl font-black tracking-tight text-[#071527]">{report.title}</h2><p className="mt-3 text-sm font-bold text-slate-400">Sådan kan en færdig Naetwork-analyse se ud.</p></div><section className="mt-7"><h3 className="text-sm font-black uppercase tracking-[.18em] text-slate-400">1. Personens egne ord</h3><p className="mt-3 rounded-2xl bg-slate-50 p-4 text-sm leading-7 text-slate-700">{report.words}</p></section><section className="mt-7"><h3 className="text-sm font-black uppercase tracking-[.18em] text-slate-400">2. Det Naetwork forstår</h3><p className="mt-3 text-sm leading-7 text-slate-700">{report.understood}</p></section><section className="mt-7"><h3 className="text-sm font-black uppercase tracking-[.18em] text-slate-400">3. Behovet bag forklaringen</h3><p className="mt-3 text-sm leading-7 text-slate-700">{report.need}</p></section><section className="mt-7"><h3 className="text-sm font-black uppercase tracking-[.18em] text-slate-400">4. Anbefalet opgave</h3><p className="mt-3 text-sm leading-7 text-slate-700">{report.task}</p></section><div className="mt-7 grid gap-5 md:grid-cols-2"><section><h3 className="text-sm font-black uppercase tracking-[.18em] text-slate-400">Scope</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{scope.map((item) => <li key={item}>• {item}</li>)}</ul></section><section><h3 className="text-sm font-black uppercase tracking-[.18em] text-slate-400">Ikke nu</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{notNow.map((item) => <li key={item}>• {item}</li>)}</ul></section></div><section className="mt-7"><h3 className="text-sm font-black uppercase tracking-[.18em] text-slate-400">Åbne spørgsmål</h3><ul className="mt-3 grid gap-2 text-sm leading-6 text-slate-700 md:grid-cols-2">{questions.map((item) => <li key={item} className="rounded-2xl bg-slate-50 p-3">{item}</li>)}</ul></section><section className="mt-7 rounded-3xl bg-[#071527] p-5 text-white"><h3 className="text-xs font-black uppercase tracking-[.18em] text-emerald-200">Anbefalet specialistretning</h3><p className="mt-3 text-lg font-black">{report.specialist}</p></section></article>;
}

export function AccountTaskCreateV13Static() {
  const [checked, setChecked] = useState(false);
  const [loggedIn, setLoggedIn] = useState(false);
  const [sent, setSent] = useState(false);
  const [need, setNeed] = useState("");
  const [context, setContext] = useState("");

  useEffect(() => { fetch("/api/account/dashboard").then((r) => setLoggedIn(r.ok)).catch(() => setLoggedIn(false)).finally(() => setChecked(true)); }, []);

  return <Shell><section className="mx-auto grid max-w-6xl gap-8 py-12 lg:grid-cols-[.82fr_1.18fr] lg:items-start lg:py-20"><div><p className="text-sm font-black uppercase tracking-[.22em] text-[#3f8f83]">Opret opgave</p><h1 className="mt-4 text-5xl font-black leading-[.95] tracking-[-0.05em] text-[#071527] md:text-7xl">Se hvordan Naetwork gør et uklart behov klart.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Før du opretter din egen opgave, kan du se et konkret eksempel på den analyse og klarhed, Naetwork arbejder hen imod.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row">{checked && loggedIn ? <a href="#start" className="rounded-full bg-[#071527] px-6 py-3 text-center text-sm font-black text-white">Start din opgave</a> : <><Link href="/login" className="rounded-full bg-[#071527] px-6 py-3 text-center text-sm font-black text-white">Log ind for at oprette opgave</Link><Link href="/opret" className="rounded-full border border-slate-300 bg-white px-6 py-3 text-center text-sm font-black text-slate-800">Opret konto</Link></>}</div></div><StaticReport /></section><section id="start" className="mx-auto max-w-6xl pb-16">{checked && loggedIn ? <div className="rounded-[34px] border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><p className="text-sm font-black uppercase tracking-[.22em] text-[#3f8f83]">Din opgave</p><h2 className="mt-3 text-3xl font-black tracking-tight text-[#071527]">Skriv dit behov med dine egne ord.</h2>{sent ? <div className="mt-6 rounded-3xl bg-emerald-50 p-5 text-sm font-black leading-7 text-emerald-900">Tak. Din opgave er klar til Naetwork review.</div> : <><label className="mt-5 grid gap-2 text-sm font-bold text-slate-700">Hvad vil du have hjælp til?<textarea value={need} onChange={(e) => setNeed(e.target.value)} rows={5} className="resize-none rounded-2xl border border-slate-200 px-4 py-3 text-sm leading-6 outline-none" /></label><label className="mt-4 grid gap-2 text-sm font-bold text-slate-700">Kontekst, systemer, mål eller timing<textarea value={context} onChange={(e) => setContext(e.target.value)} rows={4} className="resize-none rounded-2xl border border-slate-200 px-4 py-3 text-sm leading-6 outline-none" /></label><button onClick={() => setSent(true)} disabled={need.trim().length < 20} className="mt-5 min-h-[50px] w-full rounded-full bg-[#071527] px-6 py-3 text-sm font-black text-white disabled:opacity-40">Send til Naetwork review</button><p className="mt-3 text-xs font-bold text-slate-400">Eksemplet ovenfor viser formatet. Din egen opgave går videre til review.</p></>}</div> : <div className="rounded-[34px] border border-slate-200 bg-white p-6 text-center shadow-sm"><h2 className="text-3xl font-black text-[#071527]">Log ind for at oprette din egen opgave.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-7 text-slate-600">Eksemplet er åbent for alle. Din egen opgave kræver konto, så den kan gemmes og følges.</p></div>}</section></Shell>;
}
