// Bilingual content. All copy lives here. `dictionaries.en` and `dictionaries.da`
// share the same shape — TypeScript enforces that every string exists in both.

export const site = {
  name: "Naetwork",
  tagline: "Et netværk der udvikler dit netværk — og bekæmper kræft.",
  city: "Copenhagen",
  url: "https://naetwork.vercel.app",
  donateUrl: "#",
  formEndpoint: "",
};

const en = {
  tagline: "A network that develops your network — and fights cancer.",
  currency: "DKK",
  nav: {
    links: [
      { label: "How it works", href: "#how" },
      { label: "Marketplace", href: "#marketplace" },
      { label: "Impact", href: "#impact" },
      { label: "Companies", href: "#companies" },
      { label: "FAQ", href: "#faq" },
    ],
    mentor: "Mentor",
    book: "Book a session",
  },
  hero: {
    eyebrow: "· Build your network  · Fight cancer  · One year",
    titleA: "A network that",
    titleB: "develops your network.",
    titleEmph: "And fights cancer.",
    body: "Naetwork is Denmark's professional network united around one purpose for one year. You build valuable connections. Your sessions fund the fight against cancer.",
    primary: "Join for free",
    secondary: "See how it works",
    equation: [
      { value: "300 DKK", label: "you donate" },
      { value: "100%", label: "to Kræftens Bekæmpelse" },
      { value: "0 DKK", label: "kept by the platform" },
    ],
    browse: "See how it works",
    howMeta: "60 min · 300 DKK",
    seePros: "See available professionals",
    badges: ["100% donated directly via MobilePay", "Platform never holds funds", "Voluntary, non-profit"],
    countdownLabel: "Platform closes in:",
    countdownUnits: { days: "DAYS", hours: "HRS", minutes: "MIN" },
  },
  how: {
    eyebrow: "How it works",
    title: "Three steps. No catch.",
    steps: [
      { title: "Pick a professional", body: "Browse experienced volunteers across consulting, finance, tech, marketing and more. Real names, real roles." },
      { title: "Book your hour", body: "Choose a time that works. Sessions are 60 minutes, online or in person — you decide the focus." },
      { title: "Donate 300 DKK", body: "Pay via MobilePay directly to Kræftens Bekæmpelse. The platform never receives, holds or touches the money." },
    ],
  },
  ledger: {
    eyebrow: "The arithmetic",
    title: "An honest ledger.",
    body: "The model is deliberately plain. There is no margin, no subscription and no hidden fee. One donated hour becomes one full donation.",
    sessionLabel: "One session",
    rows: [
      { label: "Candidate pays", value: "300 DKK", note: "" },
      { label: "Professional's fee", value: "0 DKK", note: "time donated" },
      { label: "Platform fee", value: "0 DKK", note: "non-profit" },
    ],
    totalLabel: "To Kræftens Bekæmpelse",
    caption: "= 100% of what you pay",
    note: "We direct donations to Kræftens Bekæmpelse. We do not describe this as a formal partnership unless one has been confirmed.",
  },
  twoWays: {
    eyebrow: "Two sides, one purpose",
    candidate: {
      kicker: "For candidates",
      title: "Sharpen your edge. Fund the fight.",
      body: "Book an hour with an experienced professional. Practice your case, get CV feedback, or talk through a career decision. Your payment: 300 DKK, directly to Kræftens Bekæmpelse.",
      points: ["Case & interview practice", "Honest CV and profile feedback", "Career and mentoring conversations"],
      cta: "Book a session",
    },
    professional: {
      kicker: "For professionals",
      title: "Give an hour. In your name. Make a difference.",
      body: "Donate your expertise to the next generation of professionals. You choose your hours and format. Every session you hold is a direct donation to cancer research.",
      points: ["Choose your hours and format", "Help candidates you'd want in your industry", "Every session = one donation"],
      cta: "Become a mentor",
    },
  },
  whyOneYear: {
    eyebrow: "One year. On purpose.",
    title: "Why does the platform close after one year?",
    body: "Because it forces focus. Because it gives you a reason to act now. Because Denmark doesn't need another platform — it needs one clear moment.\n\nFor one year, we bring the country's professionals together around something bigger than career goals and CV updates. Then we close. With a total donation. And a shared story.",
    pillars: [
      { title: "Urgency", line1: "\"Now or never\"", line2: "" },
      { title: "Exclusivity", line1: "You're part of the cohort", line2: "that made it happen." },
      { title: "Focus", line1: "One purpose.", line2: "No distractions." },
    ],
  },
  impactTracker: {
    eyebrow: "Live impact",
    title: "What we've raised so far.",
    stats: [
      { value: "0", prefix: "", suffix: " DKK", label: "Total donated to Kræftens Bekæmpelse" },
      { value: "0", prefix: "", suffix: "", label: "Sessions completed" },
      { value: "0", prefix: "", suffix: "", label: "Professionals signed up" },
    ],
    note: "All donations go directly via MobilePay to Kræftens Bekæmpelse. We never see the money.",
  },
  marketplace: {
    eyebrow: "Marketplace preview",
    title: "Who you can learn from.",
    body: "Professionals from across Danish business. They donate their time. You donate 300 DKK. The marketplace opens soon — these are example profiles.",
    badge: "Example profile",
    meta: "60 min · 300 DKK",
    request: "Request",
    profiles: [
      { role: "Management Consultant", field: "Strategy & Operations", initials: "MC", tags: ["Case practice", "Interview prep"] },
      { role: "Investment Banking Associate", field: "M&A · Coverage", initials: "IB", tags: ["Interview prep", "CV review"] },
      { role: "Product Manager", field: "Tech / SaaS", initials: "PM", tags: ["Career advice", "Mentoring"] },
      { role: "Brand & Marketing Lead", field: "Consumer", initials: "BM", tags: ["Portfolio review", "Mentoring"] },
      { role: "Data Scientist", field: "Analytics & ML", initials: "DS", tags: ["Case practice", "Career advice"] },
      { role: "Startup Founder", field: "Early-stage", initials: "SF", tags: ["Business sparring", "Mentoring"] },
    ],
  },
  companies: {
    eyebrow: "For companies",
    title: "Is your company in?",
    body: "Let your employees book career sessions as part of their professional development. 100% of the payment goes to Kræftens Bekæmpelse. You get a company dashboard showing your total contribution.",
    points: [
      { title: "Invest in your people's careers", body: "Let your team book career sessions as part of their development. Real, experienced professionals. Real conversations." },
      { title: "100% of the budget goes to Kræftens Bekæmpelse", body: "No fees, no held funds. The model is easy to explain to a board, a CSR lead or a journalist." },
      { title: "Show your contribution on the impact page", body: "Your company's total donation is tracked and visible. Concrete, auditable, honest." },
    ],
    cta: "Contact us about a company agreement",
  },
  journey: {
    eyebrow: "Launch journey",
    title: "Six months to launch.",
    body: "We are building openly and at a steady pace — from concept to a live marketplace.",
    phases: [
      { month: "Feb 2027", title: "Concept & foundation", body: "Lock the model, ship the first site, confirm the donation flow." },
      { month: "Mar 2027", title: "First professionals", body: "Onboard a small, hand-picked group across a few industries." },
      { month: "Apr 2027", title: "Closed pilot", body: "Run the first real sessions with a limited group of candidates." },
      { month: "May 2027", title: "Refine & document", body: "Improve booking, sharpen the marketplace, document impact honestly." },
      { month: "Jun 2027", title: "Open the marketplace", body: "Open booking more broadly and grow the pool of professionals." },
      { month: "Jul 2027", title: "Public launch", body: "Launch publicly and invite candidates, professionals and partners." },
    ],
  },
  trust: {
    eyebrow: "Why people trust us",
    title: "Quiet credibility, by design.",
    body: "No marketing fluff. No hidden costs. The standards we'd expect from a serious institution.",
    cards: [
      { icon: "shield", title: "Real professionals, real names", body: "Every live profile shows a real name, title and employer — no anonymous profiles in the marketplace." },
      { icon: "heart", title: "100% goes to the cause", body: "Candidates donate directly via MobilePay. Naetwork does not receive, hold or deduct any part of it." },
      { icon: "scale", title: "Honest claims", body: "We support Kræftens Bekæmpelse via direct donations — we do not claim partnership unless confirmed." },
    ],
  },
  founder: {
    eyebrow: "A note from the founder",
    quote: "Career preparation should be accessible. Every session helps a candidate move forward — and supports a cause that affects us all.",
    meta: "Voluntary team · Copenhagen",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions, answered plainly.",
    items: [
      { q: "What do I get as a candidate?", a: "Sixty minutes with an experienced professional — for case practice, interview prep, CV feedback, mentoring or business sparring. You choose who you book and what to focus on." },
      { q: "Where does the 300 DKK go?", a: "The full amount is donated directly to Kræftens Bekæmpelse, paid by you via MobilePay. Naetwork does not receive, hold or deduct any part of it." },
      { q: "Are the professionals paid?", a: "No. Professionals donate their time. They are never paid for a session." },
      { q: "Are you partnered with Kræftens Bekæmpelse?", a: "We direct donations to Kræftens Bekæmpelse. We do not describe this as a formal partnership unless one has been confirmed." },
      { q: "Who is this for?", a: "Students, young professionals and anyone preparing for the next step — and experienced professionals who want to give back an hour at a time." },
      { q: "Why does the platform only run for one year?", a: "It's a deliberate choice. One year creates urgency, focus, and a shared story. When the year ends, we close the platform with a total donation and a clear impact report." },
    ],
  },
  finalCta: {
    eyebrow: "Open to candidates & professionals",
    title: "Be part of the year Danish business stood up to cancer.",
    primary: "Join for free",
    secondary: "Become a mentor",
  },
  emailCapture: {
    eyebrow: "Be part of it from day one",
    title: "Be part from day one.",
    body: "Sign up and be among the first to shape the Naetwork year.",
    cta: "Join for free",
    note: "Free to join. Sessions cost 300 DKK — everything goes to Kræftens Bekæmpelse.",
  },
  footer: {
    blurb: "Denmark's professional network united for one year around one purpose: building careers and fighting cancer.",
    columns: [
      { title: "Platform", links: [ { label: "How it works", href: "#how" }, { label: "Marketplace", href: "#marketplace" }, { label: "Impact", href: "#impact" }, { label: "Launch journey", href: "#journey" } ] },
      { title: "Participate", links: [ { label: "Join for free", href: "#book-candidate" }, { label: "Become a mentor", href: "#book-professional" }, { label: "Partner with us", href: "#book-company" }, { label: "Privacy", href: "/privacy" } ] },
    ],
    legal: "Naetwork is a voluntary, non-profit initiative. Donations are directed to Kræftens Bekæmpelse. We do not claim a formal partnership unless one has been confirmed.",
  },
  modal: {
    intents: { candidate: "I want guidance", professional: "I want to mentor", company: "We're a company" },
    candidate: { title: "Request a session", sub: "Tell us what you want to work on. At launch you book a 60-minute session and donate 300 DKK via MobilePay to Kræftens Bekæmpelse." },
    professional: { title: "Offer your time", sub: "Give an hour, on your terms. We'll be in touch as we onboard professionals ahead of launch." },
    company: { title: "Partner with us", sub: "Tell us a little about your organisation and how you'd like to take part." },
    focusOptions: ["Case practice", "Interview prep", "CV / profile feedback", "Mentoring", "Business sparring"],
    fields: { name: "Full name", email: "Email", expertise: "Your role & field (e.g. Strategy Consultant)", company: "Company", note: "Anything we should know? (optional)" },
    submit: "Submit",
    submitting: "Sending…",
    disclaimer: "No payment now. Donations are made via MobilePay at the session.",
    errName: "Please enter your name.",
    errEmail: "Please enter a valid email.",
    errGeneric: "Something went wrong. Please try again or email us.",
    successTitle: "Thank you — you're on the list.",
    successBody: "We'll reach out as we open sessions ahead of launch. Every session becomes a direct donation to Kræftens Bekæmpelse.",
    done: "Done",
  },
};

const da: typeof en = {
  tagline: "Et netværk der udvikler dit netværk — og bekæmper kræft.",
  currency: "kr.",
  nav: {
    links: [
      { label: "Sådan virker det", href: "#how" },
      { label: "Markedsplads", href: "#marketplace" },
      { label: "Effekt", href: "#impact" },
      { label: "Virksomheder", href: "#companies" },
      { label: "FAQ", href: "#faq" },
    ],
    mentor: "Mentor",
    book: "Book en session",
  },
  hero: {
    eyebrow: "· Byg dit netværk  · Bekæmp kræft  · Ét år",
    titleA: "Et netværk der",
    titleB: "udvikler dit netværk.",
    titleEmph: "Og bekæmper kræft.",
    body: "Naetwork er Danmarks erhvervsnetværk samlet om ét formål i ét år. Du bygger værdifulde relationer. Dine sessioner finansierer kampen mod kræft.",
    primary: "Tilmeld dig gratis",
    secondary: "Se hvordan det virker",
    equation: [
      { value: "300 kr.", label: "du donerer" },
      { value: "100 %", label: "til Kræftens Bekæmpelse" },
      { value: "0 kr.", label: "platformen beholder" },
    ],
    browse: "Se hvordan det virker",
    howMeta: "60 min · 300 kr.",
    seePros: "Se ledige professionelle",
    badges: ["100 % doneres direkte via MobilePay", "Platformen holder aldrig midler", "Frivilligt, non-profit"],
    countdownLabel: "Platformen lukker om:",
    countdownUnits: { days: "DAGE", hours: "TIMER", minutes: "MIN" },
  },
  how: {
    eyebrow: "Sådan virker det",
    title: "Tre trin. Ingen hage.",
    steps: [
      { title: "Vælg en professionel", body: "Find erfarne frivillige på tværs af consulting, finans, tech, marketing og mere. Rigtige navne, rigtige roller." },
      { title: "Book din time", body: "Vælg et tidspunkt der passer. Sessioner er 60 minutter, online eller fysisk — du bestemmer fokus." },
      { title: "Donér 300 kr.", body: "Betal via MobilePay direkte til Kræftens Bekæmpelse. Platformen modtager, holder eller rører aldrig pengene." },
    ],
  },
  ledger: {
    eyebrow: "Regnestykket",
    title: "Et ærligt regnskab.",
    body: "Modellen er bevidst enkel. Ingen avance, intet abonnement, ingen skjulte gebyrer. Én doneret time bliver til én fuld donation.",
    sessionLabel: "Én session",
    rows: [
      { label: "Kandidaten betaler", value: "300 kr.", note: "" },
      { label: "Den professionelles honorar", value: "0 kr.", note: "tid doneret" },
      { label: "Platformsgebyr", value: "0 kr.", note: "non-profit" },
    ],
    totalLabel: "Til Kræftens Bekæmpelse",
    caption: "= 100 % af det du betaler",
    note: "Vi sender donationer til Kræftens Bekæmpelse. Vi beskriver det ikke som et formelt partnerskab, medmindre et er bekræftet.",
  },
  twoWays: {
    eyebrow: "To sider, ét formål",
    candidate: {
      kicker: "For professionelle",
      title: "Skærp dit edge. Finansier kampen.",
      body: "Book en time med en erfaren professionel. Øv din case, få feedback på dit CV, eller tal igennem en karrierebeslutning. Din betaling: 300 kr., direkte til Kræftens Bekæmpelse.",
      points: ["Case- og interviewtræning", "Ærlig CV- og profilfeedback", "Karriere- og mentorsamtaler"],
      cta: "Book en session",
    },
    professional: {
      kicker: "For bidragsydende professionelle",
      title: "Giv en time. I dit navn. Gør en forskel.",
      body: "Donér din ekspertise til næste generation af professionelle. Du bestemmer dine timer og format. Hvert session du holder er en direkte donation til kræftforskning.",
      points: ["Vælg dine timer og format", "Hjælp kandidater du gerne vil se i din branche", "Hvert session = én donation"],
      cta: "Bliv mentor",
    },
  },
  whyOneYear: {
    eyebrow: "Ét år. Med vilje.",
    title: "Hvorfor lukker vi om ét år?",
    body: "Fordi det tvinger os til at fokusere. Fordi det giver dig en grund til at handle nu. Fordi Danmarks erhvervsliv ikke behøver endnu en platform — det behøver ét klart moment.\n\nI ét år samler vi landets professionelle om noget der er større end karrieremål og CV-opdateringer. Og så lukker vi. Med en total donation. Og en fælles historie.",
    pillars: [
      { title: "Urgency", line1: "\"Nu eller aldrig\"", line2: "" },
      { title: "Eksklusivitet", line1: "Du er en del af det", line2: "kohorte der lavede det." },
      { title: "Fokus", line1: "Ét formål.", line2: "Ingen distraktioner." },
    ],
  },
  impactTracker: {
    eyebrow: "Live effekt",
    title: "Hvad vi har rejst så langt.",
    stats: [
      { value: "0", prefix: "", suffix: " kr.", label: "Samlet doneret til Kræftens Bekæmpelse" },
      { value: "0", prefix: "", suffix: "", label: "Sessioner gennemført" },
      { value: "0", prefix: "", suffix: "", label: "Professionelle tilmeldt" },
    ],
    note: "Alle donationer sker direkte via MobilePay til Kræftens Bekæmpelse. Vi ser aldrig pengene.",
  },
  marketplace: {
    eyebrow: "Markedsplads (preview)",
    title: "Hvem du kan lære af.",
    body: "Professionelle fra hele det danske erhvervsliv. De donerer deres tid. Du donerer 300 kr. Markedspladsen åbner snart — disse er eksempel-profiler.",
    badge: "Eksempelprofil",
    meta: "60 min · 300 kr.",
    request: "Anmod",
    profiles: [
      { role: "Management-konsulent", field: "Strategi & drift", initials: "MC", tags: ["Case-træning", "Interviewforberedelse"] },
      { role: "Investment Banking Associate", field: "M&A · Coverage", initials: "IB", tags: ["Interviewforberedelse", "CV-gennemgang"] },
      { role: "Produktchef", field: "Tech / SaaS", initials: "PM", tags: ["Karriererådgivning", "Mentoring"] },
      { role: "Brand- & marketingchef", field: "Forbrug", initials: "BM", tags: ["Porteføljegennemgang", "Mentoring"] },
      { role: "Data Scientist", field: "Analytics & ML", initials: "DS", tags: ["Case-træning", "Karriererådgivning"] },
      { role: "Startup-stifter", field: "Tidlig fase", initials: "SF", tags: ["Forretningssparring", "Mentoring"] },
    ],
  },
  companies: {
    eyebrow: "For virksomheder",
    title: "Er din virksomhed med?",
    body: "Lad dine medarbejdere booke karriere-sessioner som en del af deres faglige udvikling. 100 % af betalingen går til Kræftens Bekæmpelse. I får et virksomheds-dashboard der viser jeres samlede bidrag.",
    points: [
      { title: "Investér i medarbejdernes karriereudvikling", body: "Lad jeres team booke karriere-sessioner som en del af deres udvikling. Rigtige, erfarne professionelle. Rigtige samtaler." },
      { title: "100 % af budgettet går til Kræftens Bekæmpelse", body: "Ingen gebyrer, ingen tilbageholdte midler. Modellen er let at forklare til en bestyrelse, en CSR-ansvarlig eller en journalist." },
      { title: "Vis jeres bidrag på impact-siden", body: "Jeres virksomheds samlede donation spores og er synlig. Konkret, reviderbar, ærlig." },
    ],
    cta: "Kontakt os om en virksomhedsaftale",
  },
  journey: {
    eyebrow: "Launch-rejse",
    title: "Seks måneder til launch.",
    body: "Vi bygger åbent og i et stabilt tempo — fra koncept til en live markedsplads.",
    phases: [
      { month: "Feb 2027", title: "Koncept & fundament", body: "Lås modellen, lancér det første site, bekræft donationsflowet." },
      { month: "Mar 2027", title: "Første professionelle", body: "Onboard en lille, håndplukket gruppe på tværs af et par brancher." },
      { month: "Apr 2027", title: "Lukket pilot", body: "Kør de første rigtige sessioner med en begrænset gruppe kandidater." },
      { month: "Maj 2027", title: "Forfin & dokumentér", body: "Forbedr booking, skærp markedspladsen, dokumentér effekt ærligt." },
      { month: "Jun 2027", title: "Åbn markedspladsen", body: "Åbn booking bredere og udvid poolen af professionelle." },
      { month: "Jul 2027", title: "Offentlig launch", body: "Lancér offentligt og inviter kandidater, professionelle og partnere." },
    ],
  },
  trust: {
    eyebrow: "Derfor stoler folk på os",
    title: "Stille troværdighed — med vilje.",
    body: "Ingen marketing-fnidder. Ingen skjulte omkostninger. Samme standarder som vi ville forvente af en seriøs institution.",
    cards: [
      { icon: "shield", title: "Rigtige professionelle, rigtige navne", body: "Hver live profil viser et rigtigt navn, titel og arbejdsgiver — ingen anonyme profiler på markedspladsen." },
      { icon: "heart", title: "100 % går til sagen", body: "Kandidater donerer direkte via MobilePay. Naetwork modtager, holder eller fratrækker ingen del af det." },
      { icon: "scale", title: "Ærlige påstande", body: "Vi støtter Kræftens Bekæmpelse via direkte donationer — vi hævder ikke partnerskab, medmindre det er bekræftet." },
    ],
  },
  founder: {
    eyebrow: "En hilsen fra stifteren",
    quote: "Karriereforberedelse bør være tilgængelig. Hver session hjælper en kandidat videre — og støtter en sag, der berører os alle.",
    meta: "Frivilligt team · København",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Spørgsmål, besvaret ligefremt.",
    items: [
      { q: "Hvad får jeg som kandidat?", a: "Tres minutter med en erfaren professionel — til case-træning, interviewforberedelse, CV-feedback, mentoring eller forretningssparring. Du vælger, hvem du booker, og hvad I fokuserer på." },
      { q: "Hvor går de 300 kr. hen?", a: "Hele beløbet doneres direkte til Kræftens Bekæmpelse, betalt af dig via MobilePay. Naetwork modtager, holder eller fratrækker ingen del af det." },
      { q: "Får de professionelle betaling?", a: "Nej. Professionelle donerer deres tid. De får aldrig betaling for en session." },
      { q: "Er I i partnerskab med Kræftens Bekæmpelse?", a: "Vi sender donationer til Kræftens Bekæmpelse. Vi beskriver det ikke som et formelt partnerskab, medmindre et er bekræftet." },
      { q: "Hvem er det for?", a: "Studerende, unge professionelle og alle, der forbereder næste skridt — og erfarne professionelle, der vil give en time tilbage ad gangen." },
      { q: "Hvorfor kører platformen kun i ét år?", a: "Det er et bevidst valg. Ét år skaber urgency, fokus og en fælles fortælling. Når året slutter, lukker vi platformen med en samlet donation og en klar effektrapport." },
    ],
  },
  finalCta: {
    eyebrow: "Åben for kandidater & professionelle",
    title: "Vær med det år Danmarks erhvervsliv rejste sig mod kræft.",
    primary: "Tilmeld dig gratis",
    secondary: "Bliv mentor",
  },
  emailCapture: {
    eyebrow: "Vær med fra dag ét",
    title: "Vær med fra dag ét.",
    body: "Tilmeld dig og vær blandt de første der former Naetwork-året.",
    cta: "Tilmeld dig gratis",
    note: "Gratis at tilmelde sig. Sessioner koster 300 kr. — alt går til Kræftens Bekæmpelse.",
  },
  footer: {
    blurb: "Danmarks erhvervsnetværk samlet i ét år om ét formål: bygge karrierer og bekæmpe kræft.",
    columns: [
      { title: "Platform", links: [ { label: "Sådan virker det", href: "#how" }, { label: "Markedsplads", href: "#marketplace" }, { label: "Effekt", href: "#impact" }, { label: "Launch-rejse", href: "#journey" } ] },
      { title: "Deltag", links: [ { label: "Tilmeld dig gratis", href: "#book-candidate" }, { label: "Bliv mentor", href: "#book-professional" }, { label: "Bliv partner", href: "#book-company" }, { label: "Privatliv", href: "/da/privatliv" } ] },
    ],
    legal: "Naetwork er et frivilligt, non-profit initiativ. Donationer sendes til Kræftens Bekæmpelse. Vi hævder ikke et formelt partnerskab, medmindre et er bekræftet.",
  },
  modal: {
    intents: { candidate: "Jeg vil have hjælp", professional: "Jeg vil mentorere", company: "Vi er en virksomhed" },
    candidate: { title: "Anmod om en session", sub: "Fortæl os, hvad du vil arbejde med. Ved launch booker du en 60-minutters session og donerer 300 kr. via MobilePay til Kræftens Bekæmpelse." },
    professional: { title: "Tilbyd din tid", sub: "Giv en time, på dine vilkår. Vi vender tilbage, efterhånden som vi onboarder professionelle inden launch." },
    company: { title: "Bliv partner", sub: "Fortæl os lidt om jeres organisation, og hvordan I gerne vil deltage." },
    focusOptions: ["Case-træning", "Interviewforberedelse", "CV-/profilfeedback", "Mentoring", "Forretningssparring"],
    fields: { name: "Fulde navn", email: "Email", expertise: "Din rolle & felt (fx Strategikonsulent)", company: "Virksomhed", note: "Noget vi bør vide? (valgfrit)" },
    submit: "Send",
    submitting: "Sender…",
    disclaimer: "Ingen betaling nu. Donationer foretages via MobilePay ved sessionen.",
    errName: "Indtast dit navn.",
    errEmail: "Indtast en gyldig email.",
    errGeneric: "Noget gik galt. Prøv igen, eller skriv til os.",
    successTitle: "Tak — du er på listen.",
    successBody: "Vi rækker ud, efterhånden som vi åbner sessioner inden launch. Hver session bliver til en direkte donation til Kræftens Bekæmpelse.",
    done: "Færdig",
  },
};

export const dictionaries = { en, da };
export type Lang = keyof typeof dictionaries;
export type Dict = typeof en;
