// Bilingual content. All copy lives here. `dictionaries.en` and `dictionaries.da`
// share the same shape — TypeScript enforces that every string exists in both.

export const site = {
  name: "Naetwork",
  tagline: "Solve cases. Build skills. Fight cancer.",
  city: "Copenhagen",
  // Update to your real domain after deploying (SEO, sitemap, share links).
  url: "https://naetwork.vercel.app",
  // Set before launch: real MobilePay / donation destination.
  donateUrl: "#",
  // Optional: paste a Formspree (or similar) endpoint to receive form submissions.
  formEndpoint: "",
};

const en = {
  tagline: "Solve cases. Build skills. Fight cancer.",
  currency: "DKK",
  nav: {
    links: [
      { label: "How it works", href: "#how" },
      { label: "Marketplace", href: "#marketplace" },
      { label: "Impact", href: "#impact" },
      { label: "Companies", href: "#companies" },
      { label: "FAQ", href: "#faq" },
    ],
    mentor: "Mentor",
    book: "Book a session",
  },
  hero: {
    eyebrow: "Solve cases · Build skills · Fight cancer",
    titleA: "One hour of expert career help.",
    titleB: "Three hundred kroner",
    titleEmph: "against cancer.",
    body: "Book a session with an experienced professional — case practice, interview prep, CV feedback or mentoring. They donate their time. You donate 300 DKK, and 100% goes directly to Kræftens Bekæmpelse.",
    primary: "Book a session",
    secondary: "Mentor someone",
    equation: [
      { value: "300 DKK", label: "you donate" },
      { value: "100%", label: "to Kræftens Bekæmpelse" },
      { value: "0 DKK", label: "kept by the platform" },
    ],
    browse: "Browse marketplace",
    howMeta: "60 min · 300 DKK",
    seePros: "See available professionals",
    badges: ["100% donated directly via MobilePay", "Platform never holds funds", "Voluntary, non-profit"],
  },
  how: {
    eyebrow: "How it works",
    title: "Three steps. No catch.",
    steps: [
      { title: "Pick a professional", body: "Browse experienced volunteers across consulting, finance, tech, marketing and more. Real names, real roles." },
      { title: "Book your hour", body: "Choose a time that works. Sessions are 60 minutes, online or in person — you decide the focus." },
      { title: "Donate 300 DKK", body: "Pay via MobilePay directly to Kræftens Bekæmpelse. The platform never receives, holds or touches the money." },
    ],
  },
  ledger: {
    eyebrow: "The arithmetic",
    title: "An honest ledger.",
    body: "The model is deliberately plain. There is no margin, no subscription and no hidden fee. One donated hour becomes one full donation.",
    sessionLabel: "One session",
    rows: [
      { label: "Candidate pays", value: "300 DKK", note: "" },
      { label: "Professional’s fee", value: "0 DKK", note: "time donated" },
      { label: "Platform fee", value: "0 DKK", note: "non-profit" },
    ],
    totalLabel: "To Kræftens Bekæmpelse",
    caption: "= 100% of what you pay",
    note: "We direct donations to Kræftens Bekæmpelse. We do not describe this as a formal partnership unless one has been confirmed.",
  },
  twoWays: {
    eyebrow: "Two sides, one purpose",
    candidate: {
      kicker: "For candidates",
      title: "Practice with people doing the work today.",
      body: "Sharpen your case technique, rehearse interviews, get honest feedback on your CV or talk through a career decision — with someone who has been where you want to go.",
      points: ["Case & interview practice", "Honest CV and profile feedback", "Career and mentoring conversations"],
      cta: "Book a session",
    },
    professional: {
      kicker: "For professionals",
      title: "Give an hour. In your name, on your terms.",
      body: "Mentor the next generation and turn your experience into a direct contribution to the fight against cancer — without changing your schedule more than an hour.",
      points: ["Choose your hours and format", "Help candidates you’d want on your team", "Every session is a direct donation"],
      cta: "Mentor someone",
    },
  },
  marketplace: {
    eyebrow: "Marketplace preview",
    title: "Who you can learn from.",
    body: "A look at the kind of professionals the marketplace is built around. The live marketplace opens in 2027 — these are example profiles, not real individuals.",
    badge: "Example profile",
    meta: "60 min · 300 DKK",
    request: "Request",
    profiles: [
      { role: "Management Consultant", field: "Strategy & Operations", initials: "MC", tags: ["Case practice", "Interview prep"] },
      { role: "Investment Banking Associate", field: "M&A · Coverage", initials: "IB", tags: ["Interview prep", "CV review"] },
      { role: "Product Manager", field: "Tech / SaaS", initials: "PM", tags: ["Career advice", "Mentoring"] },
      { role: "Brand & Marketing Lead", field: "Consumer", initials: "BM", tags: ["Portfolio review", "Mentoring"] },
      { role: "Data Scientist", field: "Analytics & ML", initials: "DS", tags: ["Case practice", "Career advice"] },
      { role: "Startup Founder", field: "Early-stage", initials: "SF", tags: ["Business sparring", "Mentoring"] },
    ],
  },
  companies: {
    eyebrow: "For companies & partners",
    title: "Back your people and a cause — without building a programme.",
    body: "A clear, low-effort way for organisations to support early careers and contribute to the fight against cancer. Your professionals give an hour; the donation does the rest.",
    points: [
      { title: "Visible, credible giving", body: "Let your team donate an hour. Every session is a direct donation to Kræftens Bekæmpelse, made in their own name." },
      { title: "Development, externalised", body: "Your people mentor candidates and sharpen their own coaching — useful experience, zero administration on your side." },
      { title: "Built to be audited", body: "No fees, no held funds, no inflated claims. The model is easy to explain to a board, a CSR lead or a journalist." },
    ],
    cta: "Talk to us about partnering",
  },
  journey: {
    eyebrow: "Launch journey",
    title: "Six months to launch.",
    body: "We are building openly and at a steady pace — from concept to a live marketplace.",
    phases: [
      { month: "Feb 2027", title: "Concept & foundation", body: "Lock the model, ship the first site, confirm the donation flow." },
      { month: "Mar 2027", title: "First professionals", body: "Onboard a small, hand-picked group across a few industries." },
      { month: "Apr 2027", title: "Closed pilot", body: "Run the first real sessions with a limited group of candidates." },
      { month: "May 2027", title: "Refine & document", body: "Improve booking, sharpen the marketplace, document impact honestly." },
      { month: "Jun 2027", title: "Open the marketplace", body: "Open booking more broadly and grow the pool of professionals." },
      { month: "Jul 2027", title: "Public launch", body: "Launch publicly and invite candidates, professionals and partners." },
    ],
  },
  trust: {
    eyebrow: "Why people trust us",
    title: "Quiet credibility, by design.",
    body: "No marketing fluff. No hidden costs. The standards we’d expect from a serious institution.",
    cards: [
      { icon: "shield", title: "Real professionals, real names", body: "Every live profile shows a real name, title and employer — no anonymous profiles in the marketplace." },
      { icon: "heart", title: "100% goes to the cause", body: "Candidates donate directly via MobilePay. Naetwork does not receive, hold or deduct any part of it." },
      { icon: "scale", title: "Honest claims", body: "We support Kræftens Bekæmpelse via direct donations — we do not claim partnership unless confirmed." },
    ],
  },
  founder: {
    eyebrow: "A note from the founder",
    quote: "Career preparation should be accessible. Every session helps a candidate move forward — and supports a cause that affects us all.",
    meta: "Voluntary team · Copenhagen",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions, answered plainly.",
    items: [
      { q: "What do I get as a candidate?", a: "Sixty minutes with an experienced professional — for case practice, interview prep, CV feedback, mentoring or business sparring. You choose who you book and what to focus on." },
      { q: "Where does the 300 DKK go?", a: "The full amount is donated directly to Kræftens Bekæmpelse, paid by you via MobilePay. Naetwork does not receive, hold or deduct any part of it." },
      { q: "Are the professionals paid?", a: "No. Professionals donate their time. They are never paid for a session." },
      { q: "Are you partnered with Kræftens Bekæmpelse?", a: "We direct donations to Kræftens Bekæmpelse. We do not describe this as a formal partnership unless one has been confirmed." },
      { q: "Who is this for?", a: "Students, young professionals and anyone preparing for the next step — and experienced professionals who want to give back an hour at a time." },
      { q: "When does it launch?", a: "We are building towards a public launch in 2027, starting with a closed pilot. The marketplace shown here is a preview of the live model." },
    ],
  },
  finalCta: {
    eyebrow: "Open to candidates & professionals",
    title: "Sixty minutes that prepare you — and matter beyond you.",
    primary: "Book a session",
    secondary: "Mentor someone",
  },
  footer: {
    blurb: "A purpose-driven marketplace where candidates get career guidance, professionals donate their time, and every session funds the fight against cancer.",
    columns: [
      { title: "Platform", links: [ { label: "How it works", href: "#how" }, { label: "Marketplace", href: "#marketplace" }, { label: "Impact", href: "#impact" }, { label: "Launch journey", href: "#journey" } ] },
      { title: "Participate", links: [ { label: "Book a session", href: "#book-candidate" }, { label: "Mentor someone", href: "#book-professional" }, { label: "Partner with us", href: "#book-company" }, { label: "Privacy", href: "/privacy" } ] },
    ],
    legal: "Naetwork is a voluntary, non-profit initiative. Donations are directed to Kræftens Bekæmpelse. We do not claim a formal partnership unless one has been confirmed.",
  },
  modal: {
    intents: { candidate: "I want guidance", professional: "I want to mentor", company: "We’re a company" },
    candidate: { title: "Request a session", sub: "Tell us what you want to work on. At launch you book a 60-minute session and donate 300 DKK via MobilePay to Kræftens Bekæmpelse." },
    professional: { title: "Offer your time", sub: "Give an hour, on your terms. We’ll be in touch as we onboard professionals ahead of launch." },
    company: { title: "Partner with us", sub: "Tell us a little about your organisation and how you’d like to take part." },
    focusOptions: ["Case practice", "Interview prep", "CV / profile feedback", "Mentoring", "Business sparring"],
    fields: { name: "Full name", email: "Email", expertise: "Your role & field (e.g. Strategy Consultant)", company: "Company", note: "Anything we should know? (optional)" },
    submit: "Submit",
    submitting: "Sending…",
    disclaimer: "No payment now. Donations are made via MobilePay at the session.",
    errName: "Please enter your name.",
    errEmail: "Please enter a valid email.",
    errGeneric: "Something went wrong. Please try again or email us.",
    successTitle: "Thank you — you’re on the list.",
    successBody: "We’ll reach out as we open sessions ahead of launch. Every session becomes a direct donation to Kræftens Bekæmpelse.",
    done: "Done",
  },
};

const da: typeof en = {
  tagline: "Løs cases. Byg kompetencer. Bekæmp kræft.",
  currency: "kr.",
  nav: {
    links: [
      { label: "Sådan virker det", href: "#how" },
      { label: "Markedsplads", href: "#marketplace" },
      { label: "Effekt", href: "#impact" },
      { label: "Virksomheder", href: "#companies" },
      { label: "FAQ", href: "#faq" },
    ],
    mentor: "Mentor",
    book: "Book en session",
  },
  hero: {
    eyebrow: "Løs cases · Byg kompetencer · Bekæmp kræft",
    titleA: "Én times karrierehjælp fra en ekspert.",
    titleB: "Tre hundrede kroner",
    titleEmph: "mod kræft.",
    body: "Book en session med en erfaren professionel — case-træning, interviewforberedelse, CV-feedback eller mentoring. De donerer deres tid. Du donerer 300 kr., og 100 % går direkte til Kræftens Bekæmpelse.",
    primary: "Book en session",
    secondary: "Bliv mentor",
    equation: [
      { value: "300 kr.", label: "du donerer" },
      { value: "100 %", label: "til Kræftens Bekæmpelse" },
      { value: "0 kr.", label: "platformen beholder" },
    ],
    browse: "Se markedspladsen",
    howMeta: "60 min · 300 kr.",
    seePros: "Se ledige professionelle",
    badges: ["100 % doneres direkte via MobilePay", "Platformen holder aldrig midler", "Frivilligt, non-profit"],
  },
  how: {
    eyebrow: "Sådan virker det",
    title: "Tre trin. Ingen hage.",
    steps: [
      { title: "Vælg en professionel", body: "Find erfarne frivillige på tværs af consulting, finans, tech, marketing og mere. Rigtige navne, rigtige roller." },
      { title: "Book din time", body: "Vælg et tidspunkt der passer. Sessioner er 60 minutter, online eller fysisk — du bestemmer fokus." },
      { title: "Donér 300 kr.", body: "Betal via MobilePay direkte til Kræftens Bekæmpelse. Platformen modtager, holder eller rører aldrig pengene." },
    ],
  },
  ledger: {
    eyebrow: "Regnestykket",
    title: "Et ærligt regnskab.",
    body: "Modellen er bevidst enkel. Ingen avance, intet abonnement, ingen skjulte gebyrer. Én doneret time bliver til én fuld donation.",
    sessionLabel: "Én session",
    rows: [
      { label: "Kandidaten betaler", value: "300 kr.", note: "" },
      { label: "Den professionelles honorar", value: "0 kr.", note: "tid doneret" },
      { label: "Platformsgebyr", value: "0 kr.", note: "non-profit" },
    ],
    totalLabel: "Til Kræftens Bekæmpelse",
    caption: "= 100 % af det du betaler",
    note: "Vi sender donationer til Kræftens Bekæmpelse. Vi beskriver det ikke som et formelt partnerskab, medmindre et er bekræftet.",
  },
  twoWays: {
    eyebrow: "To sider, ét formål",
    candidate: {
      kicker: "For kandidater",
      title: "Træn med folk der laver arbejdet i dag.",
      body: "Skærp din case-teknik, øv interviews, få ærlig feedback på dit CV eller vend en karrierebeslutning — med en der har stået, hvor du vil hen.",
      points: ["Case- og interviewtræning", "Ærlig CV- og profilfeedback", "Karriere- og mentorsamtaler"],
      cta: "Book en session",
    },
    professional: {
      kicker: "For professionelle",
      title: "Giv en time. I dit navn, på dine vilkår.",
      body: "Mentorér næste generation og gør din erfaring til et direkte bidrag i kampen mod kræft — uden at ændre din kalender mere end en time.",
      points: ["Vælg dine timer og format", "Hjælp kandidater du selv ville ansætte", "Hver session er en direkte donation"],
      cta: "Bliv mentor",
    },
  },
  marketplace: {
    eyebrow: "Markedsplads (preview)",
    title: "Hvem du kan lære af.",
    body: "Et indblik i den slags professionelle, markedspladsen bygges op om. Den live markedsplads åbner i 2027 — det her er eksempelprofiler, ikke rigtige personer.",
    badge: "Eksempelprofil",
    meta: "60 min · 300 kr.",
    request: "Anmod",
    profiles: [
      { role: "Management-konsulent", field: "Strategi & drift", initials: "MC", tags: ["Case-træning", "Interviewforberedelse"] },
      { role: "Investment Banking Associate", field: "M&A · Coverage", initials: "IB", tags: ["Interviewforberedelse", "CV-gennemgang"] },
      { role: "Produktchef", field: "Tech / SaaS", initials: "PM", tags: ["Karriererådgivning", "Mentoring"] },
      { role: "Brand- & marketingchef", field: "Forbrug", initials: "BM", tags: ["Porteføljegennemgang", "Mentoring"] },
      { role: "Data Scientist", field: "Analytics & ML", initials: "DS", tags: ["Case-træning", "Karriererådgivning"] },
      { role: "Startup-stifter", field: "Tidlig fase", initials: "SF", tags: ["Forretningssparring", "Mentoring"] },
    ],
  },
  companies: {
    eyebrow: "For virksomheder & partnere",
    title: "Bak op om jeres folk og en sag — uden at bygge et program.",
    body: "En klar, letvægts måde for organisationer at støtte tidlige karrierer og bidrage til kampen mod kræft. Jeres professionelle giver en time; donationen gør resten.",
    points: [
      { title: "Synlig, troværdig giving", body: "Lad jeres team donere en time. Hver session er en direkte donation til Kræftens Bekæmpelse, i deres eget navn." },
      { title: "Udvikling, lagt udenfor", body: "Jeres folk mentorerer kandidater og skærper deres egen coaching — nyttig erfaring, nul administration hos jer." },
      { title: "Bygget til at kunne revideres", body: "Ingen gebyrer, ingen tilbageholdte midler, ingen oppustede påstande. Modellen er let at forklare til en bestyrelse, en CSR-ansvarlig eller en journalist." },
    ],
    cta: "Tal med os om partnerskab",
  },
  journey: {
    eyebrow: "Launch-rejse",
    title: "Seks måneder til launch.",
    body: "Vi bygger åbent og i et stabilt tempo — fra koncept til en live markedsplads.",
    phases: [
      { month: "Feb 2027", title: "Koncept & fundament", body: "Lås modellen, lancér det første site, bekræft donationsflowet." },
      { month: "Mar 2027", title: "Første professionelle", body: "Onboard en lille, håndplukket gruppe på tværs af et par brancher." },
      { month: "Apr 2027", title: "Lukket pilot", body: "Kør de første rigtige sessioner med en begrænset gruppe kandidater." },
      { month: "Maj 2027", title: "Forfin & dokumentér", body: "Forbedr booking, skærp markedspladsen, dokumentér effekt ærligt." },
      { month: "Jun 2027", title: "Åbn markedspladsen", body: "Åbn booking bredere og udvid poolen af professionelle." },
      { month: "Jul 2027", title: "Offentlig launch", body: "Lancér offentligt og inviter kandidater, professionelle og partnere." },
    ],
  },
  trust: {
    eyebrow: "Derfor stoler folk på os",
    title: "Stille troværdighed — med vilje.",
    body: "Ingen marketing-fnidder. Ingen skjulte omkostninger. Samme standarder som vi ville forvente af en seriøs institution.",
    cards: [
      { icon: "shield", title: "Rigtige professionelle, rigtige navne", body: "Hver live profil viser et rigtigt navn, titel og arbejdsgiver — ingen anonyme profiler på markedspladsen." },
      { icon: "heart", title: "100 % går til sagen", body: "Kandidater donerer direkte via MobilePay. Naetwork modtager, holder eller fratrækker ingen del af det." },
      { icon: "scale", title: "Ærlige påstande", body: "Vi støtter Kræftens Bekæmpelse via direkte donationer — vi hævder ikke partnerskab, medmindre det er bekræftet." },
    ],
  },
  founder: {
    eyebrow: "En hilsen fra stifteren",
    quote: "Karriereforberedelse bør være tilgængelig. Hver session hjælper en kandidat videre — og støtter en sag, der berører os alle.",
    meta: "Frivilligt team · København",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Spørgsmål, besvaret ligefremt.",
    items: [
      { q: "Hvad får jeg som kandidat?", a: "Tres minutter med en erfaren professionel — til case-træning, interviewforberedelse, CV-feedback, mentoring eller forretningssparring. Du vælger, hvem du booker, og hvad I fokuserer på." },
      { q: "Hvor går de 300 kr. hen?", a: "Hele beløbet doneres direkte til Kræftens Bekæmpelse, betalt af dig via MobilePay. Naetwork modtager, holder eller fratrækker ingen del af det." },
      { q: "Får de professionelle betaling?", a: "Nej. Professionelle donerer deres tid. De får aldrig betaling for en session." },
      { q: "Er I i partnerskab med Kræftens Bekæmpelse?", a: "Vi sender donationer til Kræftens Bekæmpelse. Vi beskriver det ikke som et formelt partnerskab, medmindre et er bekræftet." },
      { q: "Hvem er det for?", a: "Studerende, unge professionelle og alle, der forbereder næste skridt — og erfarne professionelle, der vil give en time tilbage ad gangen." },
      { q: "Hvornår lancerer I?", a: "Vi bygger mod en offentlig launch i 2027, med start i en lukket pilot. Markedspladsen her er et preview af den live model." },
    ],
  },
  finalCta: {
    eyebrow: "Åben for kandidater & professionelle",
    title: "Tres minutter der forbereder dig — og betyder noget ud over dig.",
    primary: "Book en session",
    secondary: "Bliv mentor",
  },
  footer: {
    blurb: "En formålsdrevet markedsplads, hvor kandidater får karrierehjælp, professionelle donerer deres tid, og hver session finansierer kampen mod kræft.",
    columns: [
      { title: "Platform", links: [ { label: "Sådan virker det", href: "#how" }, { label: "Markedsplads", href: "#marketplace" }, { label: "Effekt", href: "#impact" }, { label: "Launch-rejse", href: "#journey" } ] },
      { title: "Deltag", links: [ { label: "Book en session", href: "#book-candidate" }, { label: "Bliv mentor", href: "#book-professional" }, { label: "Bliv partner", href: "#book-company" }, { label: "Privatliv", href: "/da/privatliv" } ] },
    ],
    legal: "Naetwork er et frivilligt, non-profit initiativ. Donationer sendes til Kræftens Bekæmpelse. Vi hævder ikke et formelt partnerskab, medmindre et er bekræftet.",
  },
  modal: {
    intents: { candidate: "Jeg vil have hjælp", professional: "Jeg vil mentorere", company: "Vi er en virksomhed" },
    candidate: { title: "Anmod om en session", sub: "Fortæl os, hvad du vil arbejde med. Ved launch booker du en 60-minutters session og donerer 300 kr. via MobilePay til Kræftens Bekæmpelse." },
    professional: { title: "Tilbyd din tid", sub: "Giv en time, på dine vilkår. Vi vender tilbage, efterhånden som vi onboarder professionelle inden launch." },
    company: { title: "Bliv partner", sub: "Fortæl os lidt om jeres organisation, og hvordan I gerne vil deltage." },
    focusOptions: ["Case-træning", "Interviewforberedelse", "CV-/profilfeedback", "Mentoring", "Forretningssparring"],
    fields: { name: "Fulde navn", email: "Email", expertise: "Din rolle & felt (fx Strategikonsulent)", company: "Virksomhed", note: "Noget vi bør vide? (valgfrit)" },
    submit: "Send",
    submitting: "Sender…",
    disclaimer: "Ingen betaling nu. Donationer foretages via MobilePay ved sessionen.",
    errName: "Indtast dit navn.",
    errEmail: "Indtast en gyldig email.",
    errGeneric: "Noget gik galt. Prøv igen, eller skriv til os.",
    successTitle: "Tak — du er på listen.",
    successBody: "Vi rækker ud, efterhånden som vi åbner sessioner inden launch. Hver session bliver til en direkte donation til Kræftens Bekæmpelse.",
    done: "Færdig",
  },
};

export const dictionaries = { en, da };
export type Lang = keyof typeof dictionaries;
export type Dict = typeof en;
