// Bilingual content. All copy lives here. `dictionaries.en` and `dictionaries.da`
// share the same shape — TypeScript enforces that every string exists in both.

export const site = {
  name: "Naetwork",
  tagline: "Professionelt netværk målt på resultater.",
  city: "Copenhagen",
  url: "https://naetwork.vercel.app",
  donateUrl: "#",
  formEndpoint: "",
};

const en = {
  tagline: "Professional networking measured by results.",
  currency: "DKK",
  nav: {
    links: [
      { label: "How it works", href: "#how" },
      { label: "For companies", href: "#companies" },
      { label: "Pricing", href: "/pricing" },
      { label: "FAQ", href: "#faq" },
    ],
    mentor: "For companies",
    book: "Create profile",
  },
  hero: {
    eyebrow: "Goal-based · AI-matched · Outcome-tracked",
    titleA: "The professional network",
    titleB: "measured by results.",
    titleEmph: "Not followers. Not likes.",
    body: "Set your goals. Get matched with people who complement your competencies and ambitions — not just your industry. Track what you actually achieve.",
    primary: "Create free profile →",
    secondary: "See how it works",
    equation: [
      { value: "Goal-based", label: "profile system" },
      { value: "AI-matching", label: "on complementarity" },
      { value: "Outcome", label: "tracking" },
    ],
    browse: "See how it works",
    howMeta: "Free to start",
    seePros: "Create your profile now →",
    badges: [
      "Goal-based profiles — not just CV",
      "AI-matching on complementarity",
      "Privacy-first — you control visibility",
    ],
  },
  how: {
    eyebrow: "How it works",
    title: "Four steps. Clear ROI.",
    steps: [
      { title: "Create profile + set your goals", body: "\"Looking for co-founder\", \"want to change industry\", \"recruiting senior engineers\"." },
      { title: "AI matches you with relevant profiles", body: "AI analyses complementary competencies and goals — not just job titles or industry overlap." },
      { title: "Structured introduction with context", body: "Every match comes with a clear reason. No random connection requests or cold InMail." },
    ],
  },
  ledger: {
    eyebrow: "The value equation",
    title: "A different kind of ROI.",
    body: "LinkedIn optimises for time on platform. Naetwork optimises for professional outcomes. One meeting booked, one job changed, one partnership formed.",
    countTo: 100,
    countSuffix: "%",
    sessionLabel: "Naetwork vs. LinkedIn",
    rows: [
      { label: "Optimises for", value: "Outcomes", note: "not engagement" },
      { label: "Profile type", value: "Goal-based", note: "not just CV" },
      { label: "Matching method", value: "AI", note: "complementarity" },
    ],
    totalLabel: "Outcome-focused",
    caption: "= the only metric that matters",
    note: "We measure success by what you achieve — not how many connections you have.",
  },
  twoWays: {
    eyebrow: "Who is Naetwork for?",
    candidate: {
      kicker: "For professionals",
      title: "Ambitious. Specific goals. Zero noise.",
      body: "You know where you want to go. You need the right connections to get there — not a feed full of performative content and random invitations.",
      points: [
        "Goal-based profile — state your next step",
        "AI matches on complementarity, not just industry",
        "Privacy-first — you choose who sees you",
      ],
      cta: "Create profile",
    },
    professional: {
      kicker: "For founders & entrepreneurs",
      title: "Building something. Need the right people.",
      body: "Co-founders, early hires, investors, sparring partners who understand your industry. Naetwork finds people with complementary goals — not just overlapping titles.",
      points: [
        "State what you're building and who you need",
        "AI surfaces complementary profiles",
        "Structured intros — no cold outreach",
      ],
      cta: "Create profile",
    },
  },
  marketplace: {
    eyebrow: "Goal-based profiles",
    title: "What a Naetwork profile looks like.",
    body: "Every profile starts with goals — not just work history. AI matches based on what you're trying to achieve and what you bring to the table.",
    badge: "Example profile",
    meta: "Active · Open",
    request: "Connect",
    profiles: [
      { role: "Strategy Consultant → Startup", field: "Seeking: co-founder", initials: "SC", tags: ["Building", "B2B SaaS"] },
      { role: "Senior Engineer", field: "Open to: leadership roles", initials: "SE", tags: ["Passively open", "Tech"] },
      { role: "Marketing Director", field: "Seeking: new industry", initials: "MD", tags: ["Career change", "Open"] },
      { role: "CFO / Finance Lead", field: "Seeking: scale-up", initials: "CF", tags: ["Series A+", "Open"] },
      { role: "Product Manager", field: "Seeking: early-stage", initials: "PM", tags: ["0→1", "SaaS"] },
      { role: "Early-stage Founder", field: "Seeking: investors + hires", initials: "EF", tags: ["Pre-seed", "HR Tech"] },
    ],
  },
  companies: {
    eyebrow: "For companies",
    title: "Passive talent that said yes to being found.",
    body: "Access a curated pool of professionals who have opted in to being discovered — no cold outreach, no spam, no wasted sourcing hours.",
    points: [
      { title: "Talent pipeline dashboard", body: "Track passive candidates aligned with your roles before you even post a job opening." },
      { title: "Anonymised talent search", body: "Browse opt-in profiles by goals, competencies and career stage — fully GDPR-compliant." },
      { title: "Targeted job posts", body: "Post to a curated audience of professionals whose goals match your openings. No noise." },
    ],
    cta: "See company plans",
  },
  journey: {
    eyebrow: "How it works",
    title: "Four steps to measurable ROI.",
    body: "From profile creation to tracked outcomes — Naetwork is built around professional results, not vanity metrics.",
    phases: [
      { month: "Step 1", title: "Create profile + set your goals", body: "\"I'm looking for a co-founder\", \"I want to change industry\", \"I'm recruiting senior engineers.\"" },
      { month: "Step 2", title: "AI matches you with relevant profiles", body: "AI analyses complementary competencies and goals — not just job titles or industry overlap." },
      { month: "Step 3", title: "Structured introduction — with context", body: "Every match includes a clear reason. No random connection requests or unsolicited messages." },
      { month: "Step 4", title: "Track your progress — see your ROI", body: "Meetings booked, jobs changed, partnerships formed. Naetwork measures what actually matters." },
    ],
  },
  trust: {
    eyebrow: "Why Naetwork is different",
    title: "Built for outcomes. Not engagement.",
    body: "LinkedIn built for advertisers. We built for professionals. Every design decision starts with one question: does this help you achieve your goals?",
    cards: [
      { icon: "shield", title: "Privacy-first by design", body: "You choose who sees you. Opt in to being discoverable — or stay private until you're ready." },
      { icon: "heart", title: "Quality over quantity", body: "No random connection requests. Every introduction is contextual, relevant and intentional." },
      { icon: "scale", title: "Results you can measure", body: "Track what Naetwork has helped you achieve — meetings, jobs, partnerships. Not followers." },
    ],
  },
  founder: {
    eyebrow: "A note from the founder",
    quote: "Professional networking should be measured by what you achieve — not by how many connections you accumulate. That's what Naetwork is built to do.",
    meta: "Copenhagen · Building in public",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions, answered plainly.",
    items: [
      { q: "How is Naetwork different from LinkedIn?", a: "LinkedIn optimises for time on platform — likes, comments, impressions. Naetwork optimises for professional outcomes: meetings booked, jobs changed, partnerships formed. You set goals. We measure results." },
      { q: "How does the AI matching work?", a: "You state your goals when creating your profile. Our AI analyses the complementarity between your goals and competencies and those of other members — not just industry or title overlap." },
      { q: "Who can see my profile?", a: "You control your visibility. You can be fully private, discoverable only to matched profiles, or open to companies actively recruiting." },
      { q: "Is it really free to start?", a: "Yes. The free tier includes profile creation, 3 AI matches per month and basic goal tracking — no credit card required." },
      { q: "What does the Pro+ plan include?", a: "Unlimited AI matches, priority visibility, direct messaging to matches, advanced filters, full outcome tracking and monthly AI career insights. 249 DKK/month." },
      { q: "What is the company plan?", a: "The company plan (999 DKK/month, up to 5 users) gives access to a talent pipeline dashboard, anonymised talent search, targeted job posts and team collaboration tools." },
    ],
  },
  finalCta: {
    eyebrow: "Professional networking. Measurable outcomes.",
    title: "Professional ROI — that's Naetwork.",
    primary: "Create free profile →",
    secondary: "See pricing",
  },
  footer: {
    blurb: "The professional network built around goals, not followers. AI-matched connections. Outcome-tracked results.",
    columns: [
      { title: "Platform", links: [ { label: "How it works", href: "#how" }, { label: "For companies", href: "#companies" }, { label: "Pricing", href: "/pricing" }, { label: "FAQ", href: "#faq" } ] },
      { title: "Get started", links: [ { label: "Create free profile", href: "#" }, { label: "Company plan", href: "/pricing" }, { label: "Privacy", href: "/privacy" } ] },
    ],
    legal: "Naetwork is a Copenhagen-based professional networking platform. Built to help professionals achieve real outcomes — not accumulate vanity metrics.",
  },
  modal: {
    intents: { candidate: "I'm a professional", professional: "I'm a founder", company: "We're a company" },
    candidate: { title: "Create your profile", sub: "Set your goals and get matched with professionals who complement your competencies and ambitions." },
    professional: { title: "Create your profile", sub: "Tell us what you're building and who you need. AI will find complementary profiles." },
    company: { title: "Company plan", sub: "Access opt-in talent, post targeted jobs and build your passive pipeline." },
    focusOptions: ["Looking for co-founder", "Career change", "Passive job search", "Recruiting", "Expanding network", "Finding investors"],
    fields: { name: "Full name", email: "Email", expertise: "Your role & goals", company: "Company (optional)", note: "What are you trying to achieve? (optional)" },
    submit: "Create profile",
    submitting: "Setting up…",
    disclaimer: "Free to start. No credit card required.",
    errName: "Please enter your name.",
    errEmail: "Please enter a valid email.",
    errGeneric: "Something went wrong. Please try again.",
    successTitle: "You're on the list.",
    successBody: "We'll reach out as we open access. Naetwork is built to help you achieve real professional outcomes.",
    done: "Done",
  },
};

const da: typeof en = {
  tagline: "Professionelt netværk målt på resultater.",
  currency: "kr.",
  nav: {
    links: [
      { label: "Sådan virker det", href: "#how" },
      { label: "Virksomheder", href: "#companies" },
      { label: "Priser", href: "/pricing" },
      { label: "FAQ", href: "#faq" },
    ],
    mentor: "Virksomheder",
    book: "Opret profil",
  },
  hero: {
    eyebrow: "Mål-baseret · AI-matched · Outcome-tracked",
    titleA: "Det professionelle netværk",
    titleB: "der måles på resultater.",
    titleEmph: "Ikke følgere. Ikke likes.",
    body: "Sæt dine mål. Bliv matchet med mennesker der komplementerer dine kompetencer og ambitioner — ikke bare din branche. Mål hvad du faktisk opnår.",
    primary: "Opret gratis profil →",
    secondary: "Se hvordan det virker",
    equation: [
      { value: "Mål-baseret", label: "profil-system" },
      { value: "AI-matching", label: "på komplementaritet" },
      { value: "Outcome", label: "tracking" },
    ],
    browse: "Se hvordan det virker",
    howMeta: "Gratis at starte",
    seePros: "Opret din profil nu →",
    badges: [
      "Mål-baserede profiler — ikke kun CV",
      "AI-matching på komplementaritet",
      "Privacy-first — du vælger synlighed",
    ],
  },
  how: {
    eyebrow: "Sådan virker det",
    title: "Fire trin. Klar ROI.",
    steps: [
      { title: "Opret profil + angiv dine mål", body: "\"Jeg søger medstifter\", \"Jeg vil skifte branche\", \"Jeg rekrutterer senior-ingeniører\"." },
      { title: "AI matcher dig med relevante profiler", body: "AI analyserer komplementære kompetencer og mål — ikke bare job-titler eller branche-overlap." },
      { title: "Struktureret introduktion med kontekst", body: "Hvert match leveres med en klar begrundelse. Ingen tilfældige forbindelsesanmodninger." },
    ],
  },
  ledger: {
    eyebrow: "Regnestykket",
    title: "En anden slags ROI.",
    body: "LinkedIn optimerer for tid på platformen. Naetwork optimerer for professionelle resultater. Ét møde booket, ét job skiftet, ét partnerskab formet.",
    countTo: 100,
    countSuffix: "%",
    sessionLabel: "Naetwork vs. LinkedIn",
    rows: [
      { label: "Optimerer for", value: "Resultater", note: "ikke engagement" },
      { label: "Profiltype", value: "Mål-baseret", note: "ikke kun CV" },
      { label: "Matching-metode", value: "AI", note: "komplementaritet" },
    ],
    totalLabel: "Outcome-fokuseret",
    caption: "= den eneste metrik der betyder noget",
    note: "Vi måler succes på hvad du opnår — ikke hvor mange forbindelser du har.",
  },
  twoWays: {
    eyebrow: "Hvem er Naetwork til?",
    candidate: {
      kicker: "For professionelle",
      title: "Ambitiøs. Specifikke mål. Nul støj.",
      body: "Du ved, hvor du vil hen. Du har brug for de rigtige forbindelser for at komme derhen — ikke et feed fyldt med performativt indhold og tilfældige invitationer.",
      points: [
        "Mål-baseret profil — angiv dit næste skridt",
        "AI matcher på komplementaritet, ikke bare branche",
        "Privacy-first — du vælger hvem der ser dig",
      ],
      cta: "Opret profil",
    },
    professional: {
      kicker: "For founders og iværksættere",
      title: "Du bygger noget. Du mangler de rette.",
      body: "Medstiftere, early hires, investorer, sparringspartnere der forstår din branche. Naetwork finder mennesker med komplementære mål — ikke bare overlappende titler.",
      points: [
        "Angiv hvad du bygger og hvem du mangler",
        "AI finder komplementære profiler",
        "Strukturerede introduktioner — ingen cold outreach",
      ],
      cta: "Opret profil",
    },
  },
  marketplace: {
    eyebrow: "Mål-baserede profiler",
    title: "Sådan ser en Naetwork-profil ud.",
    body: "Alle profiler starter med mål — ikke bare arbejdshistorik. AI matcher baseret på hvad du forsøger at opnå, og hvad du bringer til bordet.",
    badge: "Eksempelprofil",
    meta: "Aktiv · Åben",
    request: "Forbind",
    profiles: [
      { role: "Strategikonsulent → Startup", field: "Søger: medstifter", initials: "SK", tags: ["Bygger", "B2B SaaS"] },
      { role: "Senior Engineer", field: "Åben for: lederroller", initials: "SE", tags: ["Passivt åben", "Tech"] },
      { role: "Marketing Director", field: "Søger: ny branche", initials: "MD", tags: ["Karriereskifte", "Åben"] },
      { role: "CFO / Finance Lead", field: "Søger: scale-up", initials: "CF", tags: ["Series A+", "Åben"] },
      { role: "Produktchef", field: "Søger: early-stage", initials: "PM", tags: ["0→1", "SaaS"] },
      { role: "Early-stage Founder", field: "Søger: investorer + ansatte", initials: "EF", tags: ["Pre-seed", "HR Tech"] },
    ],
  },
  companies: {
    eyebrow: "For virksomheder",
    title: "Passivt talent der sagde ja til at blive fundet.",
    body: "Adgang til en curated pool af professionelle der har tilmeldt sig til at blive opdaget — ingen cold outreach, ingen spam, ingen spildte sourcings-timer.",
    points: [
      { title: "Talent pipeline dashboard", body: "Track passive kandidater der matcher dine roller — inden du overhovedet slår stillingen op." },
      { title: "Anonymiseret talent-search", body: "Søg i opt-in profiler efter mål, kompetencer og karrieretrin — fuldt GDPR-compliant." },
      { title: "Målrettede jobopslag", body: "Slå op til et curated publikum af professionelle, hvis mål matcher dine åbne stillinger. Ingen støj." },
    ],
    cta: "Se virksomhedsplaner",
  },
  journey: {
    eyebrow: "Sådan virker det",
    title: "Fire trin til målbar ROI.",
    body: "Fra profiloprettelse til trackede outcomes — Naetwork er bygget omkring professionelle resultater, ikke vanity metrics.",
    phases: [
      { month: "Trin 1", title: "Opret profil + angiv dine mål", body: "\"Jeg søger medstifter\", \"Jeg vil skifte branche\", \"Jeg rekrutterer senior-ingeniører.\"" },
      { month: "Trin 2", title: "AI matcher dig med relevante profiler", body: "AI analyserer komplementære kompetencer og mål — ikke bare job-titler eller branche-overlap." },
      { month: "Trin 3", title: "Struktureret introduktion — med kontekst", body: "Hvert match leveres med en klar begrundelse. Ingen tilfældige forbindelsesanmodninger eller cold InMail." },
      { month: "Trin 4", title: "Fremskridt tracked — du ser din ROI", body: "Møder booket, jobs skiftet, partnerskaber formet. Naetwork måler det der faktisk betyder noget." },
    ],
  },
  trust: {
    eyebrow: "Derfor er Naetwork anderledes",
    title: "Bygget til resultater. Ikke engagement.",
    body: "LinkedIn er bygget til annoncører. Vi er bygget til professionelle. Hvert design-valg starter med ét spørgsmål: hjælper dette dig med at nå dine mål?",
    cards: [
      { icon: "shield", title: "Privacy-first by design", body: "Du vælger hvem der ser dig. Tilmeld dig til at blive opdaget — eller hold dig privat, til du er klar." },
      { icon: "heart", title: "Kvalitet frem for kvantitet", body: "Ingen tilfældige forbindelsesanmodninger. Hver introduktion er kontekstuel, relevant og intentionel." },
      { icon: "scale", title: "Resultater du kan måle", body: "Track hvad Naetwork har hjulpet dig med at opnå — møder, jobs, partnerskaber. Ikke følgere." },
    ],
  },
  founder: {
    eyebrow: "En hilsen fra stifteren",
    quote: "Professionelt netværk bør måles på hvad du opnår — ikke på hvor mange forbindelser du akkumulerer. Det er det, Naetwork er bygget til.",
    meta: "København · Bygger i offentlighed",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Spørgsmål, besvaret ligefremt.",
    items: [
      { q: "Hvordan er Naetwork anderledes end LinkedIn?", a: "LinkedIn optimerer for tid på platformen — likes, kommentarer, impressions. Naetwork optimerer for professionelle resultater: møder booket, jobs skiftet, partnerskaber formet. Du sætter mål. Vi måler resultater." },
      { q: "Hvordan fungerer AI-matching?", a: "Du angiver dine mål, når du opretter din profil. Vores AI analyserer komplementariteten mellem dine mål og kompetencer og andre medlemmers — ikke bare branche- eller titeloverlab." },
      { q: "Hvem kan se min profil?", a: "Du styrer din synlighed. Du kan være fuldt privat, kun synlig for matchede profiler, eller åben for virksomheder der aktivt rekrutterer." },
      { q: "Er det virkelig gratis at starte?", a: "Ja. Gratisplanen inkluderer profiloprettelse, 3 AI-matches per måned og grundlæggende mål-tracking — intet kreditkort kræves." },
      { q: "Hvad inkluderer Professionel+-planen?", a: "Ubegrænsede AI-matches, prioriteret synlighed, direkte besked til matches, avancerede filtre, fuld outcome-tracking og månedlige AI-karriere-insights. 249 kr/md." },
      { q: "Hvad er virksomhedsplanen?", a: "Virksomhedsplanen (999 kr/md, op til 5 brugere) giver adgang til talent pipeline dashboard, anonymiseret talent-search, målrettede jobopslag og team-samarbejdsværktøjer." },
    ],
  },
  finalCta: {
    eyebrow: "Professionelt netværk. Målbart udbytte.",
    title: "Professionel ROI — det er Naetwork.",
    primary: "Opret gratis profil →",
    secondary: "Se priser",
  },
  footer: {
    blurb: "Det professionelle netværk bygget om mål, ikke følgere. AI-matchede forbindelser. Outcome-trackede resultater.",
    columns: [
      { title: "Platform", links: [ { label: "Sådan virker det", href: "#how" }, { label: "Virksomheder", href: "#companies" }, { label: "Priser", href: "/pricing" }, { label: "FAQ", href: "#faq" } ] },
      { title: "Kom i gang", links: [ { label: "Opret gratis profil", href: "#" }, { label: "Virksomhedsplan", href: "/pricing" }, { label: "Privatliv", href: "/da/privatliv" } ] },
    ],
    legal: "Naetwork er en københavnsk professionel netværksplatform. Bygget til at hjælpe professionelle med at opnå reelle resultater — ikke akkumulere vanity metrics.",
  },
  modal: {
    intents: { candidate: "Jeg er professionel", professional: "Jeg er founder", company: "Vi er en virksomhed" },
    candidate: { title: "Opret din profil", sub: "Sæt dine mål og bliv matchet med professionelle der komplementerer dine kompetencer og ambitioner." },
    professional: { title: "Opret din profil", sub: "Fortæl os hvad du bygger og hvem du mangler. AI finder komplementære profiler." },
    company: { title: "Virksomhedsplan", sub: "Adgang til opt-in talent, målrettede jobopslag og byg din passive pipeline." },
    focusOptions: ["Søger medstifter", "Karriereskifte", "Passiv jobsøgning", "Rekruttering", "Netværksudvidelse", "Finder investorer"],
    fields: { name: "Fulde navn", email: "Email", expertise: "Din rolle og mål", company: "Virksomhed (valgfrit)", note: "Hvad forsøger du at opnå? (valgfrit)" },
    submit: "Opret profil",
    submitting: "Sætter op…",
    disclaimer: "Gratis at starte. Intet kreditkort kræves.",
    errName: "Indtast dit navn.",
    errEmail: "Indtast en gyldig email.",
    errGeneric: "Noget gik galt. Prøv igen.",
    successTitle: "Du er på listen.",
    successBody: "Vi rækker ud, efterhånden som vi åbner adgang. Naetwork er bygget til at hjælpe dig med at opnå reelle professionelle resultater.",
    done: "Færdig",
  },
};

export const dictionaries = { en, da };
export type Lang = keyof typeof dictionaries;
export type Dict = typeof en;
